
server:
    servlet:
        context-path: "/passport"
    port: 8000

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/passport
        username: postgres
        password: postgres
    data:
        mongodb:
            host: localhost
            port: 27018
            database: passport
    redis:
        host: localhost
        port: 6379