name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-maven@v1
        with:
          maven-version: 3.6.3

      - name: Build and package with Maven
        run: mvn -B clean package

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is an automated release created by GitHub Actions.
          draft: false
          prerelease: false

      - name: Checkout publish-maven-action
        uses: actions/checkout@v2
        with:
          repository: MavenPublish/publish-maven-action
          ref: v1

      - name: Publish to GitHub Maven
        uses: MavenPublish/publish-maven-action@v1
        with:
          server-id: github
          repository-url: https://maven.pkg.github.com/fulusihq/${{ github.repository }}
          pom-file: ./pom.xml
          file: ./target/*.jar
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
